version: "3.9"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reservas
      MYSQL_USER: reservas
      MYSQL_PASSWORD: password
    ports:
      - "33062:3306"
    volumes:
        - db_data:/var/lib/mysql

  api:
    container_name: api
    build:
        context: docker
        dockerfile: Dockerfile
    command: sh -c "npm install && npm run start"
    user: 1000:1000
    working_dir: /app
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    volumes:
        - .:/app

volumes:
    db_data:
